[colophon]
= Architecture

[mermaid, title="Turbo Photobook Mind Map"]
....
mindmap
  root((<br/>Turbo<br/>Photobook))
    Documentation
    ::icon(fa fa-file)
      Asciidoc
      ::icon(fa fa-book)
        Mermaid
        ::icon(fa fa-chart-line)
    Implementation
      ::icon(fa fa-code)
      MongoDB 8
      ::icon(fa fa-leaf)
      Node JS 20
      ::icon(fa fa-cube)
        Vite
        React
      GraalVM Java 21<br>&lpar;pick one&rpar;
      ::icon(fa fa-mug-hot)
         Micronaut
         Quarkus
         Spring Boot
    Deployment
      ::icon(fa fa-paper-plane)
      Java Hotspot jar package JIT
      GraalVM native executable AOT
      Containerized JIT application
      Containerized AOT application
....

[mermaid, title="Software Architecture"]
....
block-beta
columns 2
block:per:2
    columns 2
    persistance["Persistance"]:1
    mongo[("MongoDB")]
    style per fill:#9d9,stroke:#333,stroke-width:4px
end
blockArrowLink<["Uses"]>(up, down):2
block:app
        columns 2
        application["application"]:2
        rest["API Rest"]
        backend(["Java Framework<br/>(Micronaut, Quarkus, Spring Boot)"]):1
        ui["User interface"]
        react(["React<br/>Single Page Application"]):1
        style backend fill:#fdd,stroke:#333,stroke-width:4px
        style app fill:#99d,stroke:#333,stroke-width:4px
    end
....
