# CI workflow to build AsciiDoc to PDF using Maven
name: Build AsciiDoc to PDF

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@main

      - name: Setup JDK 21
        uses: actions/setup-java@main
        with:
          java-version: 21
          distribution: 'corretto'
          cache: maven

      - name: Set up Node.js
        uses: actions/setup-node@main
        with:
          node-version: '20'

      - name: Install Mermaid CLI
        run: npm install -g @mermaid-js/mermaid-cli

      - name: Verify Mermaid CLI installation
        run: mmdc --version

      - name: Build with Maven
        run: mvn clean package

      - name: Convert AsciiDoc to PDF
        run: |
          mvn clean asciidoctor:process-asciidoc@asciidoc-to-pdf
